name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Discord EC2 Manager Docker Image
      run: docker build . --file Dockerfile --tag discord-ec2-manager:no_userdata_$(date +%s)
